/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITestProtocolFactory__factory } from "./ITestProtocolFactory__factory";
export { TestProtocolFactory__factory } from "./TestProtocolFactory__factory";
