/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testProtocolFactorySol from "./TestProtocolFactory.sol";
export { TestERC20Factory__factory } from "./TestERC20Factory__factory";
export { TestProtocol__factory } from "./TestProtocol__factory";
