/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TestSol from './ERC20.test.sol';
import type * as interfaces from './interfaces';

export type { erc20TestSol };

export type { interfaces };
export type { Package } from './Package';
