"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.erc20TestSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.erc20TestSol = require("./ERC20.test.sol");
